# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s

  external_labels:
    monitor: jumziLabs

scrape_configs:
- job_name: prometheus
  honor_labels: true
  static_configs:
  - targets: ['localhost:9090']

- job_name: jumziPi
  honor_labels: true
  static_configs:
  - targets: ['host.docker.internal:9100']

- job_name: jumziWin
  honor_labels: true
  static_configs:
  - targets: ['192.168.1.7:9182', '192.168.1.7:2003']
